### PR TITLE
Contributing Guidelines

### PR DESCRIPTION
**Pull request by akhmadiy**
Add Submission Guidelines
Add Commit Message Format

### CODE REVIEW

**Comment by dalisoft** [comment]
@akhmadiy thank you for contributing but please improve section related to commits. 

Should be like 
- fix(route): fixed infinite loop
- docs(readme): fixed typo
- feat: added new option or feat(options): added new option

**Comment by dalisoft** [comment]
This is requirement as new versions are released automatically by these commits

**Comment by akhmadiy** [comment]
@dalisoft I fix that and add more commit examples please check

**Review by dalisoft — APPROVED** [review]
Looks nice. Thank you

**Pull request merged**
